package com.aplus.ldata.api.enums;

public enum UserAction {
    CREATE_TASK,
    GOOGLE_REGISTRATION,
    EMAIL_PASSWORD_REGISTRATION,
    CREATE_LIST,
    CREATE_BUDGET,
    CREATE_HABIT,
    START_TIMER,
    CREATE_EXPENSE,
    CREATE_INCOME,
    EDIT_INCOME,
    EDIT_EXPENSE
}
